import type { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialUserServiceSchema1789990707351 implements MigrationInterface {
  name = 'InitialUserServiceSchema1789990707351';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" uuid NOT NULL,
        "nickname" character varying(30) NOT NULL,
        "profile_image_key" character varying(500),
        "status" character varying(30) NOT NULL,
        "suspended_until" TIMESTAMPTZ,
        "withdrawal_requested_at" TIMESTAMPTZ,
        "withdrawal_deadline_at" TIMESTAMPTZ,
        "withdrawn_at" TIMESTAMPTZ,
        "onboarding_completed_at" TIMESTAMPTZ,
        "created_at" TIMESTAMPTZ NOT NULL,
        "updated_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "pk_users" PRIMARY KEY ("id"),
        CONSTRAINT "chk_users_status"
          CHECK ("status" IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWAL_PENDING', 'WITHDRAWN'))
      )
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX "uq_users_nickname_lower" ON "users" (LOWER("nickname"))
    `);

    await queryRunner.query(`
      CREATE TABLE "oauth_accounts" (
        "id" uuid NOT NULL,
        "user_id" uuid NOT NULL,
        "provider" character varying NOT NULL,
        "provider_user_id" character varying NOT NULL,
        "provider_email" character varying,
        "created_at" TIMESTAMPTZ NOT NULL,
        "updated_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "pk_oauth_accounts" PRIMARY KEY ("id"),
        CONSTRAINT "uq_oauth_accounts_provider_provider_user_id"
          UNIQUE ("provider", "provider_user_id"),
        CONSTRAINT "uq_oauth_accounts_user_id_provider" UNIQUE ("user_id", "provider"),
        CONSTRAINT "fk_oauth_accounts_user_id"
          FOREIGN KEY ("user_id") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "terms" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code" character varying NOT NULL,
        "version" character varying NOT NULL,
        "required" boolean NOT NULL,
        "document_url" character varying NOT NULL,
        "effective_at" TIMESTAMPTZ NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "pk_terms" PRIMARY KEY ("id"),
        CONSTRAINT "uq_terms_code_version" UNIQUE ("code", "version")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "user_term_consents" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "user_id" uuid NOT NULL,
        "term_id" bigint NOT NULL,
        "agreed_at" TIMESTAMPTZ NOT NULL,
        "revoked_at" TIMESTAMPTZ,
        CONSTRAINT "pk_user_term_consents" PRIMARY KEY ("id"),
        CONSTRAINT "uq_user_term_consents_user_id_term_id" UNIQUE ("user_id", "term_id"),
        CONSTRAINT "fk_user_term_consents_user_id"
          FOREIGN KEY ("user_id") REFERENCES "users"("id"),
        CONSTRAINT "fk_user_term_consents_term_id"
          FOREIGN KEY ("term_id") REFERENCES "terms"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "badges" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "code" character varying NOT NULL,
        "name" character varying NOT NULL,
        "description" character varying,
        "image_key" character varying,
        "active" boolean NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "pk_badges" PRIMARY KEY ("id"),
        CONSTRAINT "uq_badges_code" UNIQUE ("code")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "user_badges" (
        "user_id" uuid NOT NULL,
        "badge_id" bigint NOT NULL,
        "granted_at" TIMESTAMPTZ NOT NULL,
        "revoked_at" TIMESTAMPTZ,
        CONSTRAINT "pk_user_badges" PRIMARY KEY ("user_id", "badge_id"),
        CONSTRAINT "fk_user_badges_user_id"
          FOREIGN KEY ("user_id") REFERENCES "users"("id"),
        CONSTRAINT "fk_user_badges_badge_id"
          FOREIGN KEY ("badge_id") REFERENCES "badges"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "user_blocks" (
        "blocker_user_id" uuid NOT NULL,
        "blocked_user_id" uuid NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "pk_user_blocks" PRIMARY KEY ("blocker_user_id", "blocked_user_id"),
        CONSTRAINT "chk_user_blocks_not_self"
          CHECK ("blocker_user_id" <> "blocked_user_id"),
        CONSTRAINT "fk_user_blocks_blocker_user_id"
          FOREIGN KEY ("blocker_user_id") REFERENCES "users"("id"),
        CONSTRAINT "fk_user_blocks_blocked_user_id"
          FOREIGN KEY ("blocked_user_id") REFERENCES "users"("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "outbox_events" (
        "event_id" uuid NOT NULL,
        "aggregate_id" uuid NOT NULL,
        "event_type" character varying NOT NULL,
        "payload" jsonb NOT NULL,
        "status" character varying NOT NULL,
        "publish_attempts" integer NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL,
        "published_at" TIMESTAMPTZ,
        CONSTRAINT "pk_outbox_events" PRIMARY KEY ("event_id")
      )
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "outbox_events"');
    await queryRunner.query('DROP TABLE "user_blocks"');
    await queryRunner.query('DROP TABLE "user_badges"');
    await queryRunner.query('DROP TABLE "badges"');
    await queryRunner.query('DROP TABLE "user_term_consents"');
    await queryRunner.query('DROP TABLE "terms"');
    await queryRunner.query('DROP TABLE "oauth_accounts"');
    await queryRunner.query('DROP INDEX "uq_users_nickname_lower"');
    await queryRunner.query('DROP TABLE "users"');
  }
}
