services:
  cassandra:
    image: cassandra:4.1
    ports:
      - '9042:9042'
    volumes:
      - map-cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ['CMD-SHELL', 'cqlsh -e "DESCRIBE KEYSPACES" >/dev/null 2>&1']
      interval: 10s
      timeout: 10s
      retries: 30
  redis:
    image: redis:7-alpine
    ports:
      - '6381:6379'
volumes:
  map-cassandra-data:
